workspace:
  root: C:\BATCH_FIRE
  logs: ${workspace.root}\logs
  files: ${workspace.root}\files
  data: ${workspace.root}\data

server:
  port: ${port:8080}

spring:
  application:
    name: batchfire

######## LOGGING-SETTINGS ##########
logging:
  level:
    root: info
    com.hyekyoung.batchstudy.batchfire: info

  ## LOGBACK SETTINGS
  config: classpath:logback/logback-spring.xml
  file:
    service: sb
    home: ${workspace.logs}
    server: local
    name: ${logging.file.home}\${logging.file.server}\${logging.file.server}_${logging.file.service}.log # ADMIN SERVER READ LOG FILE PATH

########## INTERFACE-INFO ###########
interface:
### INTERFACE SYSTEM CONNECT INFO ###
  connect-info:
    jco:
      erp:
        use-able: false
        destination: "erp"
        client: "100"
        user: "012011"
        password: "Info#12345"
        language: "en"
        pool-capacity: "3"
        pool-peak-limit: "10"
        host: "172.17.0.36" #DEV
        system-id: "ERP_DEV"
        host-type: true #host 연결 구분
        system-number: "00"
        group:
        r3name:
        connection-timeout: 30000
        timeout-check-period: 60000
        max-wait-time: 30000
  mapping-info:
    IF_ERP_SF_0001:
      interface-id: "IF_ERP_SF_0001"
      chunk-size: 500
      source-system: "erp"
      source-endpoint: "RFC_NAME"
      target-system: "gateway"
      target-endpoint: "/api/test1"